name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Attach zip to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components
          zip -r ../espeasy_p2p.zip espeasy_p2p

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: espeasy_p2p.zip
